Hooks:PostHook(BlackMarketTweakData, "_init_projectiles", "wz_projectilestweak_init", function(self, tweak_data)

	self.projectiles.wz_prj_50cal = {
		unit = "units/pd2_mod_warzone/weapons/wpn_prj_50cal/wpn_prj_50cal",
		local_unit = "units/pd2_mod_warzone/weapons/wpn_prj_50cal/wpn_prj_50cal_local",
		weapon_id = "m95",
		no_cheat_count = true,
		add_trail_effect = true,
		client_authoritative = true
	}
	self._projectiles_index = {
		"wz_prj_50cal",
		"frag",
		"launcher_frag",
		"rocket_frag",
		"molotov",
		"launcher_incendiary",
		"launcher_frag_m32",
		"west_arrow",
		"west_arrow_exp",
		"dynamite",
		"bow_poison_arrow",
		"crossbow_arrow",
		"crossbow_poison_arrow",
		"crossbow_arrow_exp",
		"wpn_prj_four",
		"wpn_prj_ace",
		"wpn_prj_jav",
		"arblast_arrow",
		"arblast_poison_arrow",
		"arblast_arrow_exp",
		"frankish_arrow",
		"frankish_poison_arrow",
		"frankish_arrow_exp",
		"long_arrow",
		"long_poison_arrow",
		"long_arrow_exp",
		"launcher_incendiary_m32",
		"launcher_frag_china",
		"launcher_incendiary_china",
		"wpn_prj_hur",
		"wpn_prj_target",
		"frag_com",
		"concussion",
		"launcher_frag_arbiter",
		"launcher_incendiary_arbiter",
		"chico_injector",
		"launcher_m203",
		"rocket_ray_frag",
		"fir_com",
		"smoke_screen_grenade",
		"dada_com",
		"tag_team",
		"ecp_arrow",
		"ecp_arrow_exp",
		"ecp_arrow_poison",
		"pocket_ecm_jammer",
		"launcher_frag_slap",
		"launcher_incendiary_slap",
		"elastic_arrow",
		"elastic_arrow_poison",
		"elastic_arrow_exp"
	}
end)